# Generated by Django 4.0.5 on 2022-09-26 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
